import type { Metadata } from "next";

import Shell from "@/components/shared/Shell";
import { kaaf, peydaFaNum } from "@/fonts";
import cn from "@/utils/cn";

import "./globals.css";

export const metadata: Metadata = {
	title: "MAP Agency",
	// description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" dir="rtl">
			<body className={cn("antialiased", kaaf.variable, peydaFaNum.variable)}>
				<Shell>{children}</Shell>
			</body>
		</html>
	);
}
