import type { Metadata } from "next";

import { NuqsAdapter } from "nuqs/adapters/next/app";

import Shell from "@/components/shared/Shell";
import { kaaf, peydaFaNum } from "@/fonts";
import cn from "@/utils/cn";

import "./globals.css";

export const metadata: Metadata = {
	title: "MAP Agency",
	// description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" dir="rtl">
			<body
				className={cn(
					"overflow-x-hidden antialiased",
					kaaf.variable,
					peydaFaNum.variable,
				)}
			>
				<NuqsAdapter>
					<Shell>{children}</Shell>
				</NuqsAdapter>
			</body>
		</html>
	);
}
